version: '3.8'
services:
    php-apache-environment:
        container_name: php-apache
        build:
            context: ./php
            dockerfile: Dockerfile
        depends_on:
            - ceitdb
        volumes:
            - D:\project\borrow:/var/www/html/
        ports:
            - 8000:80
    ceitdb:
        container_name: ceitdb
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 12345678
            MYSQL_DATABASE: ceit
            MYSQL_USER: ceit
            MYSQL_PASSWORD: 12345678
        ports:
            - "9906:3306"