version: '3.8'
services:
    php-apache-environment:
        container_name: php-apache
        build:
            context: ./php
            dockerfile: ./Dockerfile
        depends_on:
            - db
        volumes:
            - D:/project/borrow:/var/www/html/
        ports:
            - 8000:80
    db:
        container_name: db
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 12345678
            MYSQL_DATABASE: borrow
            MYSQL_USER: borrow
            MYSQL_PASSWORD: 12345678
        ports:
            - "9906:3306"





